# Generated by Django 5.2.4 on 2025-11-10 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likeUsers',
            field=models.ManyToManyField(related_name='likeArticles', to=settings.AUTH_USER_MODEL),
        ),
    ]
